version: "3.9"

services:
  wi-dev:
    image: wi-dev:${VERSION}
    container_name: wi-dev_${VERSION}
    build:
      context: ${REPO_PATH}
      dockerfile: ${REPO_PATH}/docker/dev/images/Dockerfile
    ports:
      # OpenSearch REST API
      - 9200:9200
    expose:
      - 9200
    volumes:
      - ${REPO_PATH}:/home/cyb3rhq-indexer
    entrypoint: ["tail", "-f", "/dev/null"]
    user: "1000:1000"
    working_dir: /home/cyb3rhq-indexer
