name: "manager-opensearch-integration"

services:
  events-generator:
    image: cyb3rhq/indexer-events-generator
    build:
      context: ../tools/events-generator
    depends_on:
      cyb3rhq.indexer:
        condition: service_healthy
    command: bash -c "python run.py -o filebeat"
    volumes:
      - alerts:/var/ossec/logs/alerts/

  cyb3rhq.manager:
    image: cyb3rhq/cyb3rhq-manager:${CYB3RHQ_VERSION}
    depends_on:
      cyb3rhq-certs-generator:
        condition: service_completed_successfully
    hostname: cyb3rhq.manager
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - INDEXER_URL=https://cyb3rhq.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=admin
      - FILEBEAT_SSL_VERIFICATION_MODE=full
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      - SSL_KEY=/etc/ssl/filebeat.key
      - API_USERNAME=cyb3rhq-wui
      - API_PASSWORD=MyS3cr37P450r.*-
      - LOG_LEVEL=info
      - MONITORING_ENABLED=false
    volumes:
      - ./certs/root-ca-manager.pem:/etc/ssl/root-ca.pem
      - ./certs/cyb3rhq.manager.pem:/etc/ssl/filebeat.pem
      - ./certs/cyb3rhq.manager-key.pem:/etc/ssl/filebeat.key
      - ./certs/root-ca.pem:/usr/share/logstash/root-ca.pem
      - alerts:/var/ossec/logs/alerts/

  cyb3rhq.indexer:
    image: opensearchproject/opensearch:${CYB3RHQ_INDEXER_VERSION}
    depends_on:
      cyb3rhq-certs-generator:
        condition: service_completed_successfully
    hostname: cyb3rhq.indexer
    ports:
      - 9200:9200
    environment:
      - CYB3RHQ_INDEXER_VERSION=${CYB3RHQ_INDEXER_VERSION}
      - node.name=cyb3rhq.indexer
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - plugins.security.ssl.http.enabled=true
      - plugins.security.allow_default_init_securityindex=true
      - plugins.security.ssl.http.pemcert_filepath=/usr/share/opensearch/config/cyb3rhq.indexer.pem
      - plugins.security.ssl.transport.pemcert_filepath=/usr/share/opensearch/config/cyb3rhq.indexer.pem
      - plugins.security.ssl.http.pemkey_filepath=/usr/share/opensearch/config/cyb3rhq.indexer-key.pem
      - plugins.security.ssl.transport.pemkey_filepath=/usr/share/opensearch/config/cyb3rhq.indexer-key.pem
      - plugins.security.ssl.http.pemtrustedcas_filepath=/usr/share/opensearch/config/root-ca.pem
      - plugins.security.ssl.transport.pemtrustedcas_filepath=/usr/share/opensearch/config/root-ca.pem
      - plugins.security.authcz.admin_dn="CN=cyb3rhq.indexer,OU=Cyb3rhq,O=Cyb3rhq,L=California, C=US"
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - compatibility.override_main_response_version=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: curl -sku admin:admin https://localhost:9200/_cat/health | grep -q docker-cluster
      start_period: 10s
      start_interval: 3s
    volumes:
      - data:/usr/share/opensearch/data
      - ./certs/cyb3rhq.indexer.pem:/usr/share/opensearch/config/cyb3rhq.indexer.pem
      - ./certs/cyb3rhq.indexer-key.pem:/usr/share/opensearch/config/cyb3rhq.indexer-key.pem
      - ./certs/root-ca.pem:/usr/share/opensearch/config/root-ca.pem

  generate-certs-config:
    image: alpine:latest
    volumes:
      - ./config:/config
    command: |
      sh -c "
      echo '
      nodes:
        indexer:
          - name: cyb3rhq.indexer
            ip: \"cyb3rhq.indexer\"
          - name: opensearch.node
            ip: \"opensearch.node\"
        server:
          - name: cyb3rhq.manager
            ip: \"cyb3rhq.manager\"
        dashboard:
          - name: cyb3rhq.dashboard
            ip: \"cyb3rhq.dashboard\"
          - name: opensearch.dashboards
            ip: \"opensearch.dashboards\"
      ' > /config/certs.yml
      "

  cyb3rhq-certs-generator:
    image: cyb3rhq/cyb3rhq-certs-generator:${CYB3RHQ_CERTS_GENERATOR_VERSION}
    hostname: cyb3rhq-certs-generator
    environment:
      - CYB3RHQ_CERTS_GENERATOR_VERSION=${CYB3RHQ_CERTS_GENERATOR_VERSION}
    depends_on:
      generate-certs-config:
        condition: service_completed_successfully
    entrypoint: sh -c "/entrypoint.sh; chown -R 1000:999 /certificates; chmod 740 /certificates; chmod 440 /certificates/*"
    volumes:
      - ./certs/:/certificates/
      - ./config/certs.yml:/config/certs.yml

  logstash:
    depends_on:
      opensearch.node:
        condition: service_healthy
      cyb3rhq-certs-generator:
        condition: service_completed_successfully
    image: logstash-oss:${LOGSTASH_OSS_VERSION}
    build:
      context: ../logstash
      args:
        - LOGSTASH_OSS_VERSION=${LOGSTASH_OSS_VERSION}
    environment:
      LOGSTASH_OSS_VERSION: ${LOGSTASH_OSS_VERSION}
      LOG_LEVEL: info
      MONITORING_ENABLED: false
    volumes:
      - ../opensearch/logstash/pipeline:/usr/share/logstash/pipeline
      - ./certs/root-ca.pem:/etc/ssl/root-ca.pem
      - alerts:/var/ossec/logs/alerts/
    command: logstash -f /usr/share/logstash/pipeline/manager-to-opensearch.conf

  # ================================================
  # OpenSearch and OpenSearch Dashboards
  # ================================================

  opensearch.node:
    image: opensearchproject/opensearch:${OS_VERSION}
    depends_on:
      cyb3rhq-certs-generator:
        condition: service_completed_successfully
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch.node
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
    volumes:
      - ../opensearch/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - ./certs/opensearch.node-key.pem:/usr/share/opensearch/config/certs/opensearch.key
      - ./certs/opensearch.node.pem:/usr/share/opensearch/config/certs/opensearch.pem
      - ./certs/root-ca.pem:/usr/share/opensearch/config/certs/root-ca.pem
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9201:9200
      - 9600:9600
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -sku admin:admin https://opensearch.node:9200 2>&1 | grep -q 'The OpenSearch Project: https://opensearch.org/'",
        ]
      interval: 1s
      timeout: 5s
      retries: 120

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:${OS_VERSION}
    depends_on:
      opensearch.node:
        condition: service_healthy
    ports:
      - 5602:5601
    expose:
      - "5602"
    volumes:
      - ../opensearch/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
      - ./certs/:/usr/share/opensearch-dashboards/config/certs/
      - ./certs/opensearch.dashboards-key.pem:/usr/share/opensearch-dashboards/config/certs/opensearch.key
      - ./certs/opensearch.dashboards.pem:/usr/share/opensearch-dashboards/config/certs/opensearch.pem
      - ./certs/root-ca.pem:/usr/share/opensearch-dashboards/config/certs/root-ca.pem

    environment:
      - 'OPENSEARCH_HOSTS="https://opensearch.node:9200"'

volumes:
  data:
  es_certs:
  alerts:
